@startuml
'https://plantuml.com/class-diagram

package Controllers{
    class TaskController{
        - TaskService
        ..
        + getAllTasks( )
        + getTask( String )
        + createTask( Task )
        + updateTask( String, String)
        + updateTask( Boolean )
        + deleteTask( String )
    }

    class TaskService{
        - List<Task> task
        ..
        + setTasks(List<Task>)
        + fetchAllTasks()
        + fetchSpecificTask(String)
        + createOneTask(Task)
        + updateSpecificTask(String, Task)
        + deleteSpecificTask(String)
    }

    TaskService -> TaskController
}

@enduml